name: uat-deployment

on:
  push:
    branches:
      - uat

jobs:
  deploy:
    name: deploy to uat
    runs-on: ubuntu-latest
    env:
      SOURCE_DIR: ".,!.git,!.github"
      TARGET_DIR: "/var/www/uat.uavcan.org"

    steps:
    - name: Retrieve repository
      uses: actions/checkout@v1
    - name: Remove pre-deployment web directory
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: '${{ secrets.SSH_TARGET }}'
        privatekey: ${{ secrets.SSH_KEY }}
        debug: false
        command: |
          if [ -d $TARGET_DIR ]; then find $TARGET_DIR -type f -exec rm '{}' \; ; fi
    - name: Copy repository to AWS web server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ${{ env.SOURCE_DIR }}
        target: ${{ env.TARGET_DIR }}
    - name: Set file permissions and reload web server
      uses: JimCronqvist/action-ssh@master
      with:
        hosts: '${{ secrets.SSH_TARGET }}'
        privatekey: ${{ secrets.SSH_KEY }}
        debug: false
        command: |
          if [ -d $TARGET_DIR ]; then chmod 777 -R $TARGET_DIR; fi
          sudo systemctl reload apache2
          date
